# Generated by Django 5.2.2 on 2026-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRATO_PRINCIPAL', 'Prato Principal'), ('SOBREMESA', 'Sobremesa'), ('BEBIDA', 'Bebida')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
